[package]
name = "omnilinter"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.13"
clap = { version = "4.5.0", features = ["derive"] }
glob = "0.3.1"
regex = { version = "1.10.3", default-features = false, features = ["std"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
tempdir = "0.3.7"
walkdir = "2.4.0"
xdg = "2.5.2"

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
