[package]
name = "omnilinter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
glob = "0.3.1"
regex = { version = "1.10.3", default-features = false, features = ["std"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
walkdir = "2.4.0"
xdg = "2.5.2"
